import { DefaultElement } from '../internal/types'

export function isSvgChild(element: DefaultElement) {
  return !!svgTags[element.tagName] && element.tagName !== 'svg'
}

export const svgTags: Record<string, 1> = {
  animate: 1,
  circle: 1,
  clipPath: 1,
  defs: 1,
  desc: 1,
  ellipse: 1,
  feBlend: 1,
  feColorMatrix: 1,
  feComponentTransfer: 1,
  feComposite: 1,
  feConvolveMatrix: 1,
  feDiffuseLighting: 1,
  feDisplacementMap: 1,
  feDistantLight: 1,
  feFlood: 1,
  feFuncA: 1,
  feFuncB: 1,
  feFuncG: 1,
  feFuncR: 1,
  feGaussianBlur: 1,
  feImage: 1,
  feMerge: 1,
  feMergeNode: 1,
  feMorphology: 1,
  feOffset: 1,
  fePointLight: 1,
  feSpecularLighting: 1,
  feSpotLight: 1,
  feTile: 1,
  feTurbulence: 1,
  filter: 1,
  foreignObject: 1,
  g: 1,
  image: 1,
  line: 1,
  linearGradient: 1,
  marker: 1,
  mask: 1,
  metadata: 1,
  path: 1,
  pattern: 1,
  polygon: 1,
  polyline: 1,
  radialGradient: 1,
  rect: 1,
  stop: 1,
  svg: 1,
  switch: 1,
  symbol: 1,
  text: 1,
  textPath: 1,
  tspan: 1,
  use: 1,
  view: 1,
}
