import { defineGenerator } from '@alloc/codegentool'
import {
  CallExpression,
  ExportDefaultDeclaration,
  Literal,
  ObjectExpression,
  Property,
} from '@alloc/codegentool/estree'
import { dirname, relative } from 'path'
import type { PathRouterOptions } from '../'

type RouterType = 'PathRouter' | 'HashRouter'

export default <T extends RouterType = 'PathRouter'>(options: {
  /** Glob patterns for the routes to include. */
  routes: string | string[]
  outPath: string
  routerType?: T
  routerOptions?: T extends 'PathRouter' ? PathRouterOptions : {}
}) =>
  defineGenerator(({ scan, write, dedent, serialize, parseModule }) => {
    const routerType = options.routerType ?? 'PathRouter'
    const constructorArgs: string[] = [routerType]
    if (options.routerOptions) {
      constructorArgs.push(serialize(options.routerOptions))
    }

    let app = dedent`
      /* DO NOT EDIT THIS FILE. It was generated by @alien-dom/router. */
      import { App, ${routerType} } from '@alien-dom/router'

      export const app = new App(${constructorArgs})
    `

    let catchAll: string | null = null

    for (const filename of scan(options.routes)) {
      const program = parseModule(filename)

      // 1. Find the default export.
      const defaultExport = program.body.find(node => {
        return node.type === 'ExportDefaultDeclaration'
      }) as ExportDefaultDeclaration
      if (!defaultExport) {
        continue
      }

      // 2. Assert that its expression is a `defineRoute` call.
      if (!isFunctionCall(defaultExport.declaration, 'defineRoute')) {
        continue
      }

      // 3. Get the "path" property from the config object.
      const functionCall = defaultExport.declaration
      const configParam = functionCall.arguments[0] as ObjectExpression
      const pathProp = configParam.properties.find(prop =>
        isProperty(prop, 'path')
      ) as Property
      if (!pathProp) {
        continue
      }

      // 4. Get the path literal.
      const path = (pathProp.value as Literal).value as string
      if (typeof path !== 'string') {
        continue
      }

      // 5. Add the route to the app.
      const importPath = getRelativeImportPath(options.outPath, filename)
      if (path === '/(.*)') {
        catchAll = importPath
      } else {
        app += `\n  .use("${path}", () => import("${importPath}"))`
      }
    }

    if (catchAll) {
      app += `\n  .use("/(.*)", () => import("${catchAll}"))`
    }

    write(options.outPath, app + `\n`)
  })

//
// Helpers
//

type ExportExpression = ExportDefaultDeclaration['declaration']

function isFunctionCall(
  node: ExportExpression,
  name: string
): node is CallExpression {
  return (
    node.type === 'CallExpression' &&
    node.callee.type === 'Identifier' &&
    node.callee.name === name
  )
}

function isProperty(node: any, name: string): node is Property {
  return (
    node.type === 'Property' &&
    node.key.type === 'Identifier' &&
    node.key.name === name
  )
}

function getRelativeImportPath(from: string, to: string) {
  let path = relative(dirname(from), to.replace(/\.[^.]+$/, ''))
  if (!path.startsWith('.')) {
    path = './' + path
  }
  return path
}
